import { RecommendedDB } from "../interfaces";

export let RECOMMENDED_DB: RecommendedDB[] = [
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/barber_image-icon.png',
    name: 'Efrain Perez',
    rol: 'Barbero',
    focusedOn: 'Cabello crespo',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-1.jpg',
    municipallity: 'Medellín',
    hood: 'Calazans',
    cutPrice: '$40.000',
    inSite: true,
    inHome: true,
    homePrice: '$10.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/saloon_image-icon-1.jpg',
    name: 'Mariana Villa',
    rol: 'Estilista',
    focusedOn: 'Cabello rizado',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-5.jpeg',
    municipallity: 'Medellín',
    hood: 'Robledo',
    cutPrice: '$30.000',
    inSite: true,
    inHome: false,
    homePrice: 'No Aplica'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/barber_image-icon-2.png',
    name: 'Ricardo Alvarez',
    rol: 'Barbero',
    focusedOn: 'Barbas y lineas',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-4.jpg',
    municipallity: 'Bello',
    hood: 'Niquia',
    cutPrice: '$25.000',
    inSite: true,
    inHome: true,
    homePrice: '$10.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/saloon_image-icon-2.jpg',
    name: 'Juliana Acevedo',
    rol: 'Estilista',
    focusedOn: 'Cabello liso y tintura',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-6.jpg',
    municipallity: 'Medellín',
    hood: 'Poblado',
    cutPrice: '$45.000',
    inSite: true,
    inHome: true,
    homePrice: '$12.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/barber_image-icon-3.png',
    name: 'Raul Marín',
    rol: 'Barbero',
    focusedOn: 'Cabello liso',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-2.jpg',
    municipallity: 'Medellín',
    hood: 'Poblado',
    cutPrice: '$45.000',
    inSite: true,
    inHome: true,
    homePrice: '$15.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/tatoo_image-icon-2.jpg',
    name: 'Luis Vega Vega',
    rol: 'Tatuador',
    focusedOn: 'Lineas y blackwork',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-10.jpeg',
    municipallity: 'Medellín',
    hood: 'Calazans',
    sessionPrice: '$600.000',
    inSite: true,
    inHome: true,
    homePrice: '$50.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/barber_image-icon-4.jpg',
    name: 'Ivan Suarez',
    rol: 'Barbero',
    focusedOn: 'Todo tipo de cabello',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-3.jpeg',
    municipallity: 'Envigado',
    hood: 'San Lucas',
    cutPrice: '$40.000',
    inSite: true,
    inHome: false,
    homePrice: 'No Aplica'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/spa_image-icon-2.jpg',
    name: 'Zen SPA',
    rol: 'SPA',
    focusedOn: 'Hydroterapia y masajes',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-12.jpg',
    municipallity: 'Medellín',
    hood: 'Poblado',
    sessionPrice: '$150.000',
    inSite: true,
    inHome: false,
    homePrice: 'No Aplica'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/saloon-image-icon-3.png',
    name: 'Lizeth Narvaez',
    rol: 'Estilista',
    focusedOn: 'Peinado y secado',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-7.jpg',
    municipallity: 'Itagui',
    hood: 'El Palmar',
    cutPrice: '$30.000',
    inSite: false,
    inHome: true,
    homePrice: '$12.000'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/spa_image-icon-1.png',
    name: 'La palma de buda',
    rol: 'SPA',
    focusedOn: 'Masajes y relajación',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-11.jpg',
    municipallity: 'Medellín',
    hood: 'Belen',
    cutPrice: '$80.000',
    inSite: true,
    inHome: false,
    homePrice: 'No Aplica'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/tatoo_image-icon-1.jpg',
    name: 'Catalina Lopez',
    rol: 'Tatuadora',
    focusedOn: 'Acuarelas y color',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-9.jpg',
    municipallity: 'Medellín',
    hood: 'San Javier',
    sessionPrice: '$800.000',
    inSite: true,
    inHome: false,
    homePrice: 'No Aplica'
  },
  {
    iconUrl: 'https://judfernandez.github.io/BarberManager/assets/images/saloon_image-icon-4.jpg',
    name: 'Monica Castro',
    rol: 'Estilista',
    focusedOn: 'Cabello corto',
    promotionImage: 'https://judfernandez.github.io/BarberManager/assets/images/card-image-8.jpg',
    municipallity: 'Medellín',
    hood: 'Calazans',
    cutPrice: '$30.000',
    inSite: true,
    inHome: true,
    homePrice: '$15.000'
  }
]
